import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderContainer from "@/provider/ProviderContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store API",
  description: "Generated by APIXCEL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderContainer>{children}</ProviderContainer>
      </body>
    </html>
  );
}
