import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import ProviderContainer from "@/provider/ProviderContainer";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store API",
  description: "Generated by APIXCEL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <Header />
        <ProviderContainer>{children}</ProviderContainer>
        <Footer />
      </body>
    </html>
  );
}
